-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 00:07:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlServicios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlServicios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlServicios` ;
USE `controlServicios` ;

-- -----------------------------------------------------
-- Table `controlServicios`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`clientes` (
  `idcliente` INT NOT NULL,
  `correlativo` VARCHAR(5) NULL,
  `primernombre` VARCHAR(75) NULL,
  `segundonombre` VARCHAR(75) NULL,
  `primerapelldio` VARCHAR(75) NULL,
  `segundoapellido` VARCHAR(75) NULL,
  `direccion` TEXT NULL,
  `dpi` VARCHAR(15) NULL,
  `referencias` TEXT NULL,
  `telefono1` VARCHAR(40) NULL,
  `telefono2` VARCHAR(40) NULL,
  `nit` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`puestos` (
  `idpuestos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NULL,
  `descripcion` TEXT NULL,
  `nivel` INT NULL,
  PRIMARY KEY (`idpuestos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`empleados` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `telefono` VARCHAR(40) NULL,
  `direccion` VARCHAR(45) NULL,
  `puestos_idpuestos` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleados_puestos_idx` (`puestos_idpuestos` ASC) ,
  CONSTRAINT `fk_empleados_puestos`
    FOREIGN KEY (`puestos_idpuestos`)
    REFERENCES `controlServicios`.`puestos` (`idpuestos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`servicios` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tarifa` DOUBLE NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idservicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`fechacorte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`fechacorte` (
  `idfechacorte` INT NOT NULL AUTO_INCREMENT,
  `fechacorte` DATE NULL,
  PRIMARY KEY (`idfechacorte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`servicioscontratados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`servicioscontratados` (
  `mesesnopagados` INT NULL,
  `subtotal` DOUBLE NULL,
  `idcliente` INT NOT NULL,
  `idservicio` INT NOT NULL,
  `idfechacorte` INT NOT NULL,
  `idestado` INT NOT NULL,
  `contratonumero` VARCHAR(45) NULL,
  `cobropactado` DOUBLE NULL,
  `duracioncontrato` INT NULL,
  `fechainicio` DATE NULL,
  PRIMARY KEY (`idcliente`, `idservicio`),
  INDEX `fk_servicioscontratados_clientes1_idx` (`idcliente` ASC) ,
  INDEX `fk_servicioscontratados_servicios1_idx` (`idservicio` ASC) ,
  INDEX `fk_servicioscontratados_fechacorte1_idx` (`idfechacorte` ASC) ,
  INDEX `fk_servicioscontratados_estado1_idx` (`idestado` ASC) ,
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) ,
  UNIQUE INDEX `idservicio_UNIQUE` (`idservicio` ASC) ,
  CONSTRAINT `fk_servicioscontratados_clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `controlServicios`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicioscontratados_servicios1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `controlServicios`.`servicios` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicioscontratados_fechacorte1`
    FOREIGN KEY (`idfechacorte`)
    REFERENCES `controlServicios`.`fechacorte` (`idfechacorte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicioscontratados_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `controlServicios`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`cobros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`cobros` (
  `idcobro` INT NOT NULL AUTO_INCREMENT,
  `numerofactura` VARCHAR(100) NULL,
  `idempleado` INT NOT NULL,
  `fecha` DATE NULL,
  `total` DOUBLE NULL,
  `idcliente` INT NOT NULL,
  `idservicio` INT NOT NULL,
  PRIMARY KEY (`idcobro`, `idcliente`, `idservicio`),
  INDEX `fk_cobros_empleados1_idx` USING BTREE (`idempleado`) ,
  INDEX `fk_cobros_servicioscontratados1_idx` USING BTREE (`idcliente`, `idservicio`) ,
  INDEX `fecha` USING BTREE (`fecha`) ,
  CONSTRAINT `fk_cobros_empleados1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `controlServicios`.`empleados` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobros_servicioscontratados1`
    FOREIGN KEY (`idcliente` , `idservicio`)
    REFERENCES `controlServicios`.`servicioscontratados` (`idcliente` , `idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`trabajos` (
  `idtrabajos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NULL,
  `monto` VARCHAR(45) NULL,
  PRIMARY KEY (`idtrabajos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlServicios`.`trabajospendientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlServicios`.`trabajospendientes` (
  `idtrabajospendientes` INT NOT NULL AUTO_INCREMENT,
  `idtrabajos` INT NOT NULL,
  `idservicioscontratados` INT NOT NULL,
  `fechaorden` DATE NULL,
  `fecharealizar` VARCHAR(45) NULL,
  `servicioscontratados_idcliente` INT NOT NULL,
  `servicioscontratados_idservicio` INT NOT NULL,
  PRIMARY KEY (`idtrabajospendientes`, `servicioscontratados_idcliente`, `servicioscontratados_idservicio`),
  INDEX `fk_trabajospendientes_trabajos1_idx` (`idtrabajos` ASC) ,
  INDEX `fk_trabajospendientes_servicioscontratados1_idx` (`servicioscontratados_idcliente` ASC, `servicioscontratados_idservicio` ASC) ,
  CONSTRAINT `fk_trabajospendientes_trabajos1`
    FOREIGN KEY (`idtrabajos`)
    REFERENCES `controlServicios`.`trabajos` (`idtrabajos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajospendientes_servicioscontratados1`
    FOREIGN KEY (`servicioscontratados_idcliente` , `servicioscontratados_idservicio`)
    REFERENCES `controlServicios`.`servicioscontratados` (`idcliente` , `idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;